name: Pull Request

on:
  pull_request:
    branches: [master]
jobs:
  # Test
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox
      - name: Run tests
        run: tox
